# Generated by Django 5.2 on 2025-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('locations', models.CharField(max_length=200)),
                ('business_hours', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('specs', models.TextField(help_text='Specifications (e.g., dimensions, battery life, etc.)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('product_type', models.CharField(choices=[('street', 'Solar Powered Street Light'), ('driveway', 'Solar Powered Driveway Light'), ('wall', 'Solar Powered Outside Wall Light')], max_length=20)),
            ],
        ),
    ]
